name: github-pages

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "10 2 * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: oldstable
      - name: render index.html
        run: go run main.go
        env:
          SECRET_KEY: ${{secrets.SECRET_KEY}}
      - name: configure pages
        uses: actions/configure-pages@v5
      - name: upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."
      - name: deploy pages
        id: deployment
        uses: actions/deploy-pages@v4
